export const CHECKERS_NORMAL_MOVE = 'CHECKERS_NORMAL_MOVE';
export const CHECKERS_KINGS_MOVE = 'CHECKERS_KINGS_MOVE';
export const CHECKERS_CLEARING_BOARD = 'CHECKERS_CLEARING_BOARD';
export const CHECKERS_END_GAME = 'CHECKERS_END_GAME';
export const CHECKERS_CHOOSE_CHARACTER = 'CHECKERS_CHOOSE_CHARACTER';
export const CHECKERS_CHOOSE_NORMAL_CHECKER = 'CHECKERS_CHOOSE_NORMAL_CHECKER';
export const CHECKERS_CHOOSE_KINGS_CHECKER = 'CHECKERS_CHOOSE_KINGS_CHECKER';