export const TIC_TAC_TOE_MOVE = 'TIC_TAC_TOE_MOVE';
export const TIC_TAC_TOE_CLEARING_BOARD = 'TIC_TAC_TOE_CLEARING_BOARD';
export const TIC_TAC_TOE_END_GAME = 'TIC_TAC_TOE_END_GAME';
export const TIC_TAC_TOE_CHOOSE_CHARACTER = 'TIC_TAC_TOE_CHOOSE_CHARACTER';